name: PR

on:
  pull_request:
    branches:
      - master
      - alpha

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - name: pull-code
        uses: actions/checkout@v7
      - name: install-node
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: "npm"
      - name: install-dependencies
        run: |
          npm ci --legacy-peer-deps
      - name: lint
        run: |
          npm run lint
      - name: check builder schema
        run: |
          npm run check:schema
      - name: hook-code
        run: |
          npm run sync
      - name: test
        run: |
          npm run test:ci
      - name: build
        run: |
          npm run build
